/*
  Warnings:

  - The values [IN_DELIVERY,CANCELLED,READY_FOR_DELIVERY] on the enum `OrderStatus` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "OrderStatus_new" AS ENUM ('PENDING', 'WAITING_FOR_PAYMENT', 'PAYMENT_IN_PROGRESS', 'PAYMENT_CONFIRMED', 'PENDING_CONFIRMATION', 'CONFIRMED', 'REJECTED_BY_BUSINESS', 'PREPARING', 'READY_FOR_PICKUP', 'DELIVERY_PENDING', 'DELIVERY_ASSIGNED', 'DELIVERY_ACCEPTED', 'DELIVERY_REJECTED', 'DELIVERY_REASSIGNING', 'OUT_FOR_PICKUP', 'PICKED_UP', 'OUT_FOR_DELIVERY', 'DELIVERED', 'DELIVERY_FAILED', 'RETURNED', 'REFUNDED', 'COMPLETED', 'CANCELLED_BY_USER', 'CANCELLED_BY_BUSINESS', 'CANCELLED_BY_DELIVERY', 'FAILED');
ALTER TABLE "ordenes" ALTER COLUMN "estado" DROP DEFAULT;
ALTER TABLE "ordenes" ALTER COLUMN "estado" TYPE "OrderStatus_new" USING ("estado"::text::"OrderStatus_new");
ALTER TYPE "OrderStatus" RENAME TO "OrderStatus_old";
ALTER TYPE "OrderStatus_new" RENAME TO "OrderStatus";
DROP TYPE "OrderStatus_old";
ALTER TABLE "ordenes" ALTER COLUMN "estado" SET DEFAULT 'PENDING';
COMMIT;
